import '@/app/ui/global.css';
import { inter } from '@/app/ui/fonts.ts';
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Financial",
  // description: "Generated by create next app",
};
export default function RootLayout({ children, }: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
